# 网站主页标题
title: Eviadc的笔记
# 网站标题后缀
suffix: Eviadc's blog
# 作者名称(会显示在首页文章下面)
author: Eviadc
# 网站关键字
keyword: 
# 网站描述
web_description: 
# 网站语言
lang: zh-CN
# 网站建站时间
since_year: 2018
# 导航名称
menus_title:
    home: 主页
    categories: 类别
    tags: 标签
    archives: 归档
    #galleries: 相册
    #links: 链接
    #about: 关于

# 导航
menus_link:
    home: /
    categories: /categories
    tags: /tags
    archives: /archives
    #galleries: /galleries
    #links: /links
    #about: /about

# 个人信息
about: 
    author: Nathan Wang
    protrait: ''
    description: 浓浓雾中呓语山岭

# logo
logo: /images/headers_icon/logo.webp
# Icon
icon:
    favicon: /images/icon/favicon.ico # 网页标签上那个小图标 一定要用本地存储
    locked: /images/icon/locked.png
    normal: /images/icon/normal.png
    go_top: /images/icon/go_top.png
    go_bottom: /images/icon/go_bottom.png
    search: /images/icon/search.png
    aside: /images/icon/aside.png
    toggle_theme: /images/icon/toggle_theme.png
    copy: /images/icon/copy.png
    close_code_block: /images/icon/close_code_block.png
    sticky: /images/icon/sticky.png

# 每个页面的展示的图标和一句话
headers:
    home: {
        message: '这里是home',
        icon: '/images/headers_icon/logo_white.webp'
    }  # 主页
    categories:
        {
            message: "好像也没分几类",
            icon: "/images/headers_icon/categories.svg",
        }
    tags:
        {
            message: "这里是一些展示的标签",
            icon: "/images/headers_icon/tags.svg",
        }
    archives:
        {
            # 这里会替换掉两个变量{ year 年，number 总数 } 当然也可以不写这两个变量
            message: "居然一共才写了 number 篇文章！",
            message_month: "在 year 年 month 月里写了 number 篇文章！",
            message_year: "在 year 年里写了 number 篇文章！",
            icon: "/images/headers_icon/archives.svg",
        }
    #galleries:
    #    {
    #        message: "有趣的相册~（施工中）",
    #        icon: "/images/headers_icon/galleries.svg",
    #    }
    #links:
    #    {
    #        message: "一些神奇小网站~",
    #        icon: "/images/headers_icon/links.svg",
    #    }
    #about:
    #    {
    #        message: "关于我",
    #        icon: "/images/headers_icon/about.svg",
    #    }


# 网页访问统计
web_analytics:
    enable: true  # 需要改为 true
    busuanzi: true  # 不蒜子访问量统计
    baidu:  #（替换）百度统计的 Key，参见 https://tongji.baidu.com/sc-web/10000033910/home/site/getjs?siteId=13751376 代码获取中 hm.js? 后边的字符串

# Giscus
giscus:
    enable: true  # 只有为 true 才会生效
    repo: Eviadc/eviadc.github.io
    repo_id: R_kgDOPA6hVQ
    category: Ideas
    category_id: DIC_kwDOPA6hVc4Cr63Q
    mapping: pathname
    strict: 1
    reactions-enabled: 1
    emit_metadata: 0
    input_position: top


# 底部显示的图标（github 或者其他）
bottom_icon:
    # 可以多个
    - {
          # 描述名称
          name: "github",
          # 图标
          icon: "/images/bottom_icon/github.webp",
          # 跳转链接
          link: "",
      }


# 归档页是否开启侧边栏
archive_aside: true
# 标签页是否开启侧边栏
tag_aside: true
# 标签页是否开启目录
archive_toc: true
# 标签页是否开启目录
tag_toc: true

# 翻页显示上下文页数，必须是一个自然数
pagination: 3

# 搜索（如果 hexo-generator-search 启用的话）
search: true

# 懒加载（如果 hexo-lazyload-image 启用的话）
lazyload: true

# 字数统计（前端方法，不需要 hexo-wordcount）
wordcount: true

# 自动将多个空格替换成对应的 &nbsp;
replaceSpacesWithNbsp: true

# fancybox
fancybox:
    enable: true
    css: css/plugins/fancybox.css
    js: js/plugins/fancybox.umd.js

# mathjax 和 katex 用于显示数学公式，二者取其一
katex:
    enable: true
    css: /js/plugins/katex/katex.min.css # https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.css
    js: /js/plugins/katex/katex.min.js # https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/katex.min.js
    auto_render: /js/plugins/katex/auto-render.min.js # https://cdn.jsdelivr.net/npm/katex@0.16.9/dist/contrib/auto-render.min.js
    copy_tex:
        enable: true
        css: /css/plugins/copy-tex.css # https://cdn.bootcdn.net/ajax/libs/KaTeX/0.12.0/contrib/copy-tex.css
        js: /js/plugins/copy-tex.js # https://cdn.bootcdn.net/ajax/libs/KaTeX/0.12.0/contrib/copy-tex.js

# mermaid chart
# 可以配合（hexo-filter-mermaid-diagrams）
mermaid: ## mermaid url https://github.com/knsv/mermaid
  enable: true  # default true
  js: https://cdn.jsdelivr.net/npm/mermaid@11.4.0/dist/mermaid.min.js
  options: # find more api options from https://github.com/knsv/mermaid/blob/master/src/mermaidAPI.js
    #startOnload: true  // default true

# 默认的 cover (默认缩略图) 在没有填写（这里可以替换（可以是 api 也可以是固定的图））
default_cover: "/images/random_top_img/01.webp"

# 网页的 top_img，每次会从下面的列表中随机选取一张
random_top_img:
    - "/images/random_top_img/01.webp"
    - "/images/random_top_img/02.webp"
    - "/images/random_top_img/03.webp"
    - "/images/random_top_img/04.webp"
    - "/images/random_top_img/05.webp"
    - "/images/random_top_img/06.webp"
    - "/images/random_top_img/07.webp"

# 所有网页中插入的 html 语句
inject: 
  head:
  bottom:

# 如果网站需要填写 ICP 备案信息，可在这里填写
icp:
    enable: false
    icon: 
    link: 
    text: 

